apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipelinerun-nextapp-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: nextapp
    - name: source-repo
      value: git@github.ibm.com:coralie-jonvel/nextapp.git 
    - name: image-repo
      value: quay.io/cjonvel/nextapp
  pipelineRef:
    name: pipeline-nextapp
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce

