apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipelinerun-nextapp-gitops-
spec:
  serviceAccountName: pipeline
  params:
  - name: GIT_USER_NAME
    value: pipeline
  - name: GIT_USER_EMAIL
    value: pipeline@localhost
  - name: GIT_CODE_REPO
    value: git@github.com:cjonvel/cjonvel-nextapp.git   # to be changed
  - name: GIT_CODE_REVISION
    value: main
  - name: GIT_CONFIG_REPO
    value: git@github.com:cjonvel/cjonvel-nextapp-config.git    # to be changed
  - name: IMAGE_NAME
    value: de.icr.io/lab-registry/cjonvel-nextapp    # to be changed
  pipelineRef:
    name: nextapp-gitops
  workspaces:
  - name: pipeline-shared-data
    persistentVolumeClaim:
      claimName: nextapp-pipeline
  - name: github-credentials
    secret:
      secretName: github-credentials