apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipelinerun-nextapp-
spec:
  serviceAccountName: pipeline
  params:
    - name: source-repo
      value: git@github.com:cjonvel/cjonvel-nextapp.git 
    - name: image-registry
      value: de.icr.io/lab-registry/cjonvel-nextapp
    - name: app-name
      value: nextapp
  pipelineRef:
    name: pipeline-nextapp
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce

