apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-receiver
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: webhook-receiver
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggers
      - triggerbindings
      - triggertemplates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webhook-receiver
subjects:
  - kind: ServiceAccount
    name: webhook-receiver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webhook-receiver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aggregate-olm-edit-tekton-jonvel   # To be changed
subjects:
  - kind: ServiceAccount
    name: webhook-receiver
    namespace: lab-jonvel   # To be changed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregate-olm-edit-tekton
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: webhook-receiver
spec:
  params:
    - name: source-repo
      description: source repository ssh url injected from TriggerBinding
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName:  pipelinerun-nextapp-
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: pipeline-nextapp
        params:
          - name: app-name
            value: nextapp
          - name: source-repo
            value:  $(tt.params.source-repo)    #  Will be filled by git event thanks to TriggerBinding mapping
          - name: image-registry
            value: de.icr.io/lab-registry/cjonvel-nextapp   # To be changed
        workspaces:
          - name: pipeline-shared-data
            persistentVolumeClaim:
              claimName: nextapp-pipeline    # this PVC must already exist
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: webhook-receiver
spec:
  params:
    - name: source-repo
      value: $(body.repository.ssh_url)
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook-receiver
spec:
  to:
    kind: Service
    name: el-webhook-receiver
    weight: 100
  port:
    targetPort: http-listener
  wildcardPolicy: None
---