apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook-receiver
spec:
  triggers:
    - template:
        ref: webhook-receiver
      bindings:
      - ref: webhook-receiver
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: webhook-receiver
spec:
  params:
    - name: source-repo
      description: source repository ssh url injected from TriggerBinding
    - name: image-registry
      description: docker image path in container registry
    - name: source-repo-branch
      description: source repository branch injected from TriggerBinding
    - name: one-pipeline-dockerconfigjson
      description: dockerconfig for registry
    - name: git-ssh-key
      description: to access github
    - name: git-config-repo
      description: where to put kustomization files
    - name: git-username
      description: git username for commit
    - name: git-email
      description: git email for commit
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName:  pipelinerun-nextapp-
      spec:
        serviceAccountName: build-bot
        pipelineRef:
          name: pipeline-nextapp
        params:
          - name: app-name
            value: nextapp
          - name: source-repo
            value:  $(tt.params.source-repo)    #  Will be filled by git event thanks to TriggerBinding mapping
          - name: source-repo-branch
            value:  $(tt.params.source-repo-branch)    #  Will be filled by git event thanks to TriggerBinding mapping
          - name: image-registry
            value: $(tt.params.image-registry)    
          - name: GIT_CONFIG_REPO
            value: $(tt.params.git-config-repo)   
          - name: GIT_USER_NAME
            value: $(tt.params.git-username)
          - name: GIT_USER_EMAIL
            value: $(tt.params.git-email)
        workspaces:
          - name: pipeline-shared-data
            persistentVolumeClaim:
              claimName: nextapp-pipeline    # this PVC must already exist
          - name: github-credentials
            secret:
              secretName: github-credentials
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: build-bot
      secrets:
        - name: ibmcloud-cr-credentials
        - name: github-credentials
    - kind: Secret
      apiVersion: v1
      metadata:
        name: ibmcloud-cr-credentials
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(tt.params.one-pipeline-dockerconfigjson)
    - kind: Secret
      apiVersion: v1
      metadata:
        name: github-credentials
        annotations:
          tekton.dev/git-0: github.com
      type: kubernetes.io/ssh-auth
      data:
        ssh-privatekey: $(tt.params.git-ssh-key)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: webhook-receiver
spec:
  params:
    - name: source-repo
      value: $(body.repository.ssh_url)
